{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "clinicflow-frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "clinicflow-frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.port }}
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - auth-service
                  - patient-service
                  - appointment-service
                  - clinical-service
                  - notification-service
      ports:
        - port: 8081
          protocol: TCP
        - port: 8082
          protocol: TCP
        - port: 8083
          protocol: TCP
        - port: 8085
          protocol: TCP
        - port: 8084
          protocol: TCP
        - port: 9000
          protocol: TCP
{{- end }}
