global:
  imageTag: "0.1.0-local"
  imagePullPolicy: IfNotPresent

security:
  jwt:
    issuer: clinicflow-auth
    existingSecret: clinicflow-jwt
    privateKeyKey: jwt-private.pem
    publicKeyKey: jwt-public.pem

postgres:
  enabled: true
  name: postgres
  image: postgres:16-alpine
  database: clinicflow
  username: clinicflow
  password: clinicflow
  existingSecret: ""
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

rabbitmq:
  enabled: true
  name: rabbitmq
  image: rabbitmq:4.3.4-management-alpine
  username: clinicflow
  password: clinicflow
  existingSecret: ""
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

backend:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 750m
      memory: 768Mi
  services:
    auth:
      name: auth-service
      image: clinicflow/auth-service
      port: 8081
      database: clinicflow_auth
      rabbitmq: false
      jwtPrivateKey: true
    patient:
      name: patient-service
      image: clinicflow/patient-service
      port: 8082
      database: clinicflow_patient
      rabbitmq: true
      jwtPrivateKey: false
    appointment:
      name: appointment-service
      image: clinicflow/appointment-service
      port: 8083
      database: clinicflow_appointment
      rabbitmq: true
      jwtPrivateKey: false
    clinical:
      name: clinical-service
      image: clinicflow/clinical-service
      port: 8085
      database: clinicflow_clinical
      rabbitmq: true
      jwtPrivateKey: false
    notification:
      name: notification-service
      image: clinicflow/notification-service
      port: 8084
      database: clinicflow_notification
      rabbitmq: true
      jwtPrivateKey: false

frontend:
  name: frontend
  image: clinicflow/frontend
  port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s

grafanaDashboards:
  enabled: true
  label: grafana_dashboard

networkPolicy:
  enabled: true
