apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clinicflow.configName" . }}
  labels:
    {{- include "clinicflow.labels" . | nindent 4 }}
data:
  CLINICFLOW_SECURITY_JWT_ISSUER: {{ .Values.security.jwt.issuer | quote }}
  CLINICFLOW_MESSAGING_EXCHANGE: "therapy.events.exchange"
  CLINICFLOW_MESSAGING_DEAD_LETTER_EXCHANGE: "therapy.events.dlx"
  CLINICFLOW_MESSAGING_NOTIFICATION_QUEUE: "notification.events.queue"
  CLINICFLOW_MESSAGING_NOTIFICATION_DLQ: "notification.events.dlq"
  CLINICFLOW_MESSAGING_CLINICAL_QUEUE: "clinical.appointment-events.queue"
  CLINICFLOW_MESSAGING_CLINICAL_DLQ: "clinical.appointment-events.dlq"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  PATIENT_SERVICE_URL: "http://patient-service:8082"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:8083"
  CLINICAL_SERVICE_URL: "http://clinical-service:8085"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
  AUTH_SERVICE_HEALTH_URL: "http://auth-service:9000"
  PATIENT_SERVICE_HEALTH_URL: "http://patient-service:9000"
  APPOINTMENT_SERVICE_HEALTH_URL: "http://appointment-service:9000"
  CLINICAL_SERVICE_HEALTH_URL: "http://clinical-service:9000"
  NOTIFICATION_SERVICE_HEALTH_URL: "http://notification-service:9000"
