{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    {{- include "clinicflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    clinicflow.io/metrics: rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
    - name: prometheus
      port: 15692
      targetPort: prometheus
  selector:
    app.kubernetes.io/component: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    {{- include "clinicflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  serviceName: {{ .Values.rabbitmq.name }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "clinicflow.labels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image | quote }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - rabbitmq-plugins enable --offline rabbitmq_prometheus && exec rabbitmq-server
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
            - name: prometheus
              containerPort: 15692
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "clinicflow.rabbitmqSecretName" . }}
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "clinicflow.rabbitmqSecretName" . }}
                  key: password
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.rabbitmq.storage.size | quote }}
{{- end }}
