{{- if and .Values.postgres.enabled (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clinicflow.postgresSecretName" . }}
  labels:
    {{- include "clinicflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
---
{{- end }}
{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clinicflow.rabbitmqSecretName" . }}
  labels:
    {{- include "clinicflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.username | quote }}
  password: {{ .Values.rabbitmq.password | quote }}
{{- end }}
