{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clinicflow-spring-services
  labels:
    {{- include "clinicflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      clinicflow.io/metrics: spring
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clinicflow-rabbitmq
  labels:
    {{- include "clinicflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      clinicflow.io/metrics: rabbitmq
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: prometheus
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
